version = "2"
linters.default = "standard"
linters.enable = [
  "exhaustive",
  "unconvert",
  "whitespace",
  "predeclared",
  "govet",
]

[linters.settings.staticcheck]
checks = [
  "all",
  "-ST1000",
  "-ST1001",
  "-ST1003",
  "-ST1016",
  "-ST1020",
  "-ST1021",
  "-ST1022",
]
